# Generated by Django 4.0.4 on 2022-06-01 14:35

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ct', models.CharField(max_length=20)),
                ('area', models.IntegerField()),
                ('valor', models.FloatField()),
                ('data_inicio', models.DateField()),
                ('previsao_execucao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('fornecimento', models.CharField(max_length=40)),
                ('pessoafisica', models.ManyToManyField(blank=True, related_name='PessoasJuridicas', to='O2site.pessoafisica')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('qtd_asg', models.IntegerField()),
                ('observacao', models.TextField(blank=True)),
                ('endereco', models.CharField(max_length=200)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='O2site.contrato')),
                ('pessoafisica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='O2site.pessoafisica')),
                ('pessoajuridica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='O2site.pessoajuridica')),
            ],
        ),
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('choices', models.CharField(choices=[('N', 'NÃO'), ('T', 'TRANSPORTE'), ('A', 'ALIMENTAÇÃO'), ('AM', 'ALIMENTAÇÃO + TRANSPORTE')], max_length=2)),
                ('data', models.DateTimeField()),
                ('observacao', models.TextField(blank=True)),
                ('pessoafisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='O2site.pessoafisica')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='pessoafisica',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='O2site.pessoafisica'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pessoajuridica',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='O2site.pessoajuridica'),
        ),
    ]
