# Generated by Django 4.0.4 on 2022-06-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('O2site', '0003_remove_pessoajuridica_fornecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='O2site.servico'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'CLIENTE'), ('FORNECEDOR', 'FORNECEDOR')], max_length=20),
        ),
    ]
